version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: "823667002813.dkr.ecr.af-south-1.amazonaws.com/recruiter-assistant:2f3cc1cbe2d631f92ff48274afde746c4f846e8e"
    # ${GITHUB_SHA}"
    command: ./app/start.sh
    volumes:
      - .:/app
      # - .:/app/start.sh
      # - ./rag-source-knowledge:/app/rag-source-knowledge
      # - huggingface_cache:/root/.cache/huggingface  
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ELASTIC_URL=http://elasticsearch:${ELASTIC_PORT:-9200}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_API_KEY=${HF_API_KEY}
      # - TRANSFORMERS_CACHE=/root/.cache/huggingface
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy


volumes:
  postgres_data:
  elasticsearch_data:
  # huggingface_cache:  

